-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 16:53:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbArchivos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbArchivos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbArchivos` DEFAULT CHARACTER SET utf8 ;
USE `dbArchivos` ;

-- -----------------------------------------------------
-- Table `dbArchivos`.`tblUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbArchivos`.`tblUsuario` (
  `strEmail` VARCHAR(50) NOT NULL,
  `strPassword` VARCHAR(45) NOT NULL,
  `strFirstName` VARCHAR(45) NOT NULL,
  `strLastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`strEmail`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbArchivos`.`tblArchivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbArchivos`.`tblArchivos` (
  `intIdArchivo` INT NOT NULL AUTO_INCREMENT,
  `strNombreArchivo` VARCHAR(45) NOT NULL,
  `tblUsuario_strEmail` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`intIdArchivo`, `tblUsuario_strEmail`),
  CONSTRAINT `fk_tblArchivos_tblUsuario`
    FOREIGN KEY (`tblUsuario_strEmail`)
    REFERENCES `dbArchivos`.`tblUsuario` (`strEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
